FROM lukemathwalker/cargo-chef:latest AS chef
LABEL authors="jakob753951"

WORKDIR /sync

FROM chef AS planner
COPY models/ /models/
COPY sync .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /sync/recipe.json recipe.json
COPY models/ /models/
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY sync .
RUN cargo build --release --bin sync

# We do not need the Rust toolchain to run the binary!
FROM debian:bookworm AS runtime
WORKDIR /sync
COPY --from=builder /sync/target/release/sync /usr/local/bin

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y libssl3
RUN apt clean
RUN rm -rf /var/lib/apt/lists/*

HEALTHCHECK --start-period=30s --retries=5 --interval=10s --timeout=10s \
    CMD curl --fail http://localhost:7100/ping || exit 1

STOPSIGNAL sigkill
ENTRYPOINT ["/usr/local/bin/sync"]
