FROM lukemathwalker/cargo-chef:latest AS chef
LABEL authors="jakob753951"

WORKDIR /pim

FROM chef AS planner
COPY models/ /models/
COPY pim .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /pim/recipe.json recipe.json
COPY models/ /models/
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY pim .
RUN cargo build --release --bin pim

# We do not need the Rust toolchain to run the binary!
FROM debian:bookworm AS runtime
WORKDIR /pim
COPY --from=builder /pim/target/release/pim /usr/local/bin
ENTRYPOINT ["/usr/local/bin/pim"]
