FROM lukemathwalker/cargo-chef:latest AS chef
LABEL authors="jakob753951"

WORKDIR /gps

FROM chef AS planner
COPY models/ /models/
COPY gps .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /gps/recipe.json recipe.json
COPY models/ /models/
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY gps .
RUN cargo build --release --bin gps

# We do not need the Rust toolchain to run the binary!
FROM debian:bookworm AS runtime
WORKDIR /gps
COPY --from=builder /gps/target/release/gps /usr/local/bin
ENTRYPOINT ["/usr/local/bin/gps"]
