services:
  ddf_db:
    image: postgres
    container_name: ddf_database
    ports:
      - 5432:5432
    volumes:
      - ddf-storage:/var/lib/postgresql/data
      - ./ddf/db_init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=ddf
    networks:
      - my-network
  gps_db:
    image: postgres
    container_name: gps_database
    ports:
      - 5433:5432
    volumes:
      - gps-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=gps
    networks:
      - my-network
  pim_db:
    image: postgres
    container_name: pim_database
    ports:
      - 5434:5432
    volumes:
      - pim-storage:/var/lib/postgresql/data
      - ./pim/db_init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=pim
    networks:
      - my-network
  ddf_server:
    build:
      context: ./
      dockerfile: Dockerfile_ddf
    container_name: ddf_server
    environment:
      DATABASE_URL: "postgresql://admin:admin@ddf_db/ddf"
      HOST_URL: "0.0.0.0:7100"
      DOCUMENTATION_TARGET_URL: "http://localhost:7100"
    ports:
      - 7100:7100
    depends_on:
      - ddf_db
    networks:
      - my-network
  gps_server:
    build:
      context: ./
      dockerfile: Dockerfile_gps
    container_name: gps_server
    environment:
      DATABASE_URL: "postgresql://admin:admin@gps_db/gps"
      HOST_URL: "0.0.0.0:7100"
      DOCUMENTATION_TARGET_URL: "http://localhost:7200"
    ports:
      - 7200:7100
    depends_on:
      - gps_db
    networks:
      - my-network
  pim_server:
    build:
      context: ./
      dockerfile: Dockerfile_pim
    container_name: pim_server
    environment:
      DATABASE_URL: "postgresql://admin:admin@pim_db/pim"
      HOST_URL: "0.0.0.0:7100"
      DOCUMENTATION_TARGET_URL: "http://localhost:7300"
    ports:
      - 7300:7100
    depends_on:
      - pim_db
    networks:
      - my-network
  sync_tool_server:
    build:
      context: ./
      dockerfile: Dockerfile_sync_tool
    container_name: data_sync_server
    environment:
      HOST_URL: "0.0.0.0:7100"
      DOCUMENTATION_TARGET_URL: "http://localhost:7400"

      DDF_BASE_URL: "http://ddf_server:7100"
      GPS_BASE_URL: "http://gps_server:7100"
      PIM_BASE_URL: "http://pim_server:7100"
    ports:
      - 7400:7100
    depends_on:
      - ddf_server
      - gps_server
      - pim_server
    networks:
      - my-network

volumes:
  ddf-storage: {}
  gps-storage: {}
  pim-storage: {}

networks:
  my-network:
    external: false