[env]
HOST_URL = "0.0.0.0:7400"
DOCUMENTATION_TARGET_URL = "http://localhost:7400"

DDF_BASE_URL = "https://localhost:7100"
GPS_BASE_URL = "https://localhost:7200"
PIM_BASE_URL = "https://localhost:7300"